FROM centos:latest

MAINTAINER kaDDDar "https://github.com/kaDDDar/docker"

RUN yum update -y
RUN yum install -y \
    php70 \
    php70-php-opcache \
    php70-php-fpm \
    php70-php-mysqlnd \
    php70-php-common \
    php70-php-mbstring \
    php70-php-mcrypt \
    php70-php-mysqlnd \
    php70-php-xml \
    php70-php-pdo \
    php70-php-json